# percent mark notation without char creates average sting
p %[sting may have square and curley breckets in percent notation. <= this one by square brackets.]
p %{this is a string} == "this is a string"
p %{sting is generated by persent mark. <= This one by curley brackets.}
